Update tat command and tmux for better workflow
- when I kill tmux don't detach
- allow for passing a path to the tat command so I don't have to open
  the folder

diff --git a/bin/tat b/bin/tat
--- a/bin/tat
+++ b/bin/tat
@@ -2,8 +2,31 @@
 #
 # Attach or create tmux session named the same as current directory.
 
-path_name="$(basename "$PWD" | tr . -)"
-session_name=${1-$path_name}
+session_name=""
+while getopts ":s:h" opt; do
+  case $opt in
+    s) session_name="$OPTARG";;
+    h) echo "Usage: tat [-s <session_name>] [<file_path>]"; exit;;
+    \?) echo "Invalid option: -$OPTARG" >&2;;
+  esac
+done
+shift $((OPTIND - 1))
+
+file_path="$PWD"
+
+if [ $# -gt 0 ]; then
+  file_path=$(realpath "$1")
+
+  if [ ! -e "$file_path" ]; then
+    echo "Error: The specified file path does not exist."
+    exit 1
+  fi
+
+fi
+
+if [ -z "$session_name" ]; then
+  session_name="$(basename "$file_path" | tr . -)"
+fi
 
 not_in_tmux() {
   [ -z "$TMUX"  ]
@@ -14,12 +37,12 @@ session_exists() {
 }
 
 create_detached_session() {
-  (TMUX='' tmux new-session -Ad -s "$session_name")
+  (TMUX='' tmux new-session -Ad -s "$session_name" -c "$file_path")
 }
 
 create_if_needed_and_attach() {
   if not_in_tmux; then
-    tmux new-session -As "$session_name"
+    tmux new-session -As "$session_name" -c "$file_path"
   else
     if ! session_exists; then
       create_detached_session
